name: Build and deploy Node.js app to Azure Web App - auth-Tinder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install
        working-directory: Backend

      - name: Zip backend
        run: |
          cd Backend
          zip -r ../backend.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-zip
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_68510D3357CA469ABE19A02C87020FC8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3D155CC1BA0746ACB6FE46577E4A9990 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2789527F7C12430780B91CABADE7182E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: auth-Tinder
          slot-name: Production
          package: backend.zip


